/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stlorganiser.views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jean-Christophe Chatelain
 */
public class FavoritesPanel extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    /**
     * Creates new form favoritesPanel
     */
    public FavoritesPanel() {
        tableModel = new javax.swing.table.DefaultTableModel(
            new Object [][]{
            },
            new String [] {
                "Checksum","Nom", "Chemin", "Taille","Note", "Description","Temps d'impression","Support"
            }
        );
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        favoritesTable = new javax.swing.JTable();

        favoritesTable.setModel(tableModel);
        jScrollPane1.setViewportView(favoritesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void addToTable(Object[] objs){
        tableModel.addRow(objs);
    }
    
    public void removeFromTable(Object checksum){
        int index = -1;
        for (int i = tableModel.getRowCount() - 1; i >= 0; --i) {
            if(tableModel.getValueAt(i, 0).equals(checksum)){
                index = i;
                break;
            }
        }
        if(index>=0){
            tableModel.removeRow(index);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable favoritesTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
